### ISSUE TITLE
bit flag for 1989-07-13 spot value

### ISSUE THREAD

**Issue by ocoddington** [lasp/nrlssi#46]
I replaced the LASP value for sunspot darkening for 1989-07-13, which was too high because the LEAR station was counted twice because one instance had its station name in lower case.
I replaced the value with Judith's value for this day.
The corrected record is as follows. Note, that I set the bit flag to '4' which should indicate interpolated data. This is a different case, but I used it for now. The data file is sunspot_blocking_1981-12-01_2014-12-31_with_interp.txt

1989-07-13   1331.04    567.25   4

**Comment by dlindhol** [comment]
Migrated to NRLSSI-44
